---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Сервера:

    - Proxmox virtual environment:
        icon: proxmox.png
        href: https://pve.homelab.ru
        description: Сервер виртуализации
        widget:
          type: proxmox
          url: https://192.168.31.10:8006
          username: {{HOMEPAGE_VAR_PVE_USERNAME}}
          password: {{HOMEPAGE_VAR_PVE_API_KEY}}
          ignoreInsecure: true

    - Proxmox backup server:
        icon: proxmox.png
        href: https://pbs.homelab.ru
        description: Сервер резервного копирования VM 
        widget:
          type: proxmoxbackupserver
          url: https://192.168.31.203:8007
          username: {{HOMEPAGE_VAR_PBS_USERNAME}}
          password: {{HOMEPAGE_VAR_PBS_API_KEY}}
          ignoreInsecure: true

    - TrueNAS Scale:
        icon: truenas.png
        href: https://truenas.homelab.ru
        description: NAS
        widget:
          type: truenas
          url: https://192.168.31.201
          version: 2 # optional, defaults to 1
          enablePools: true # optional, defaults to false
          nasType: scale
          key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}

    - OpenWRT:
        icon: openwrt.png
        href: https://openwrt.homelab.ru
        description: Маршрутизатор
        widget:
          type: openwrt
          url: https://192.168.31.1
          username: {{HOMEPAGE_VAR_OWRT_USERNAME}}
          password: {{HOMEPAGE_VAR_OWRT_PASSWORD}}
#          interfaceName: br-lan # optional

- Сервисы:

    - Cockpit:
        icon: cockpit.png
        href: https://cockpit.homelab.ru
        description: Панель управления Podman VM
   
    - Forgejo:
        icon: forgejo.png
        href: https://forgejo.homelab.ru
        description: Хостинг кода

    - Adguard home:
        icon: adguard-home.png
        href: https://adguardhome.homelab.ru
        description: DNS-сервер
    
    - Uptime kuma:
        icon: uptime-kuma.png
        href: https://uptime-kuma.homelab.ru
        description: Мониторинг доступности
    
    - Grafana:
        icon: grafana.png
        href: https://grafana.homelab.ru
        description: Дашборды

    - Victoria metrics:
        icon: victoriametrics.png
        href: https://victoria-metrics.homelab.ru
        description: База данных метрик

    - Traefik:
        icon: traefik.png
        href: https://traefik-dashboard.homelab.ru
        description: Обратный прокси

    - Authelia:
        icon: authelia.png
        href: https://auth.homelab.ru
        description: Сервер аутентификации и авторизации

    - Syncthing:
        icon: syncthing.png
        href: https://syncthing.homelab.ru
        description: Синхронизация файлов

    - Syncthing:
        icon: syncthing.png
        href: https://127.0.0.1:8384
        description: Синхронизация файлов. Клиент ПК

    - Stirling PDF:
        icon: stirling-pdf.png
        href: https://stirling-pdf.homelab.ru
        description: PDF-редактор

    - Gotify:
        icon: gotify.png
        href: https://gotify.homelab.ru
        description: Сервер пуш-уведомлений

    - Qbittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.homelab.ru
        description: Торрент-клиент

    - MeTube:
        icon: metube.png
        href: https://metube.homelab.ru
        description: Загрузчик видео YouTube

    - 3X-UI :
        icon: 3xui.png
        href: {{HOMEPAGE_VAR_3XUI_URL}}
        description: Exit node
    
    - 3X-UI local:
        icon: 3xui.png
        href: https://pannel.homelab.ru/admin
        description: Local node

    - MiRouter AX3200:
        icon: si-xiaomi
        href: https://192.168.31.124/cgi-bin/luci/
        description: Точка доступа
    
