http:
  routers:
    forgejo:
      entryPoints:
        - "https"
      rule: "Host(`forgejo.homelab.ru`)"        # Change DOMAIN_NAME to yours
      middlewares:
        - security-headers@file
      tls: {}
      service: forgejo

  services:
    forgejo:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8086"            # Change IP Address to your proxmox instance
        passHostHeader: true
