http:
  routers:
    gotify:
      entryPoints:
        - "https"
      rule: "Host(`gotify.homelab.ru`)"        # Change DOMAIN_NAME to yours
      middlewares:
        - security-headers@file
      tls: {}
      service: gotify

  services:
    gotify:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8087"            # Change IP Address to your proxmox instance
        passHostHeader: true
