http:
 #region routers 
  routers:
    openwrt:
      entryPoints:
        - "https"
      rule: "Host(`openwrt.homelab.ru`)"        # Change DOMAIN_NAME to yours
      middlewares:
        - security-headers@file
      tls: {}
      service: openwrt

  services:
    openwrt:
      loadBalancer:
        servers:
          - url: "https://192.168.31.1"            # Change IP Address to your proxmox instance
        passHostHeader: true
