http:
 #region routers 
  routers:
    qbittorrent:
      entryPoints:
        - "https"
      rule: "Host(`qbittorrent.homelab.ru`)"        # Change DOMAIN_NAME to yours
      middlewares:
        - security-headers@file
      tls: {}
      service: qbittorrent

  services:
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8082"            # Change IP Address to your proxmox instance
        passHostHeader: true
